[tool.poetry]
name = "ipyfacets"
version = "0.1.2"
description = "The facets project(https://github.com/PAIR-code/facets) wrapper for jupyter"
authors = ["porkbeans <mizuo.taka@gmail.com>"]
readme = "README.rst"
homepage = "https://github.com/porkbeans/jupyter-facets"
repository = "https://github.com/porkbeans/jupyter-facets"
classifiers = [
	"Framework :: Jupyter",
	"Topic :: Scientific/Engineering :: Visualization",
]

[tool.poetry.dependencies]
python = ">=3.6"
pandas = "^0.24.2"
numpy = "^1.16"
protobuf = "^3.8"
ipython = "^7.5"

[tool.poetry.dev-dependencies]
jupyter = "^1.0"
jupyterlab = "^0.35.6"
openml = "^0.9.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
